spring:
  application:
    name: hello-service
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include:  bus-refresh
  security:
    enabled: false
server:
  port: 8081
